Insert into tb_category (name, created_At) values ('Pizzas', NOW());
Insert into tb_category (name, created_At) values ('Lanches', NOW());
Insert into tb_category (name, created_At) values ('Porções', NOW());
Insert into tb_category (name, created_At) values ('Bebidas', NOW());

INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Alho e Óleo', 37.0, 14.0, NOW(), 'Massa (média), molho, queijo, presunto, tomate, champignon, azeitona, alho, azeite de oliva, orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Atum', 39.0, 15.0, NOW(), 'Massa (média), molho, queijo, presunto, azeitona, pepino, atum, oreégano, (cebola opcional)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Bolonhesa', 41.0, 16.0, NOW(), 'Massa (média), molho, carne de 1ª, queijo, ovo cozido, champignon, azeitona, queijo provolone, orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Bacon', 41.0, 16.0, NOW(), 'Massa (média), molho, queijo, presunto, bacon, champignon, azeitona, orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Calabreza', 39.0, 15.0, NOW(), 'Massa (média), molho, queijo, presunto, calabreza picada, azeitona, oregano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Champignon', 41.0, 16.0, NOW(), 'Massa (média), molho, queijo, presunto, tomate, champignon, azeitona, orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Frango', 39.0, 15.0, NOW(), 'Massa (média), molho, queijo, frango catupery, azeitona, orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Lombinho', 41.0, 16.0, NOW(), 'Massa (média), molho, queijo, presunto, lombinho, azeitona, orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Mussarela', 30.0, 11.0, NOW(), 'Massa (média), molho, queijo, mussarela, tomate, azeitona, orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Napolitana', 33.0, 12.0, NOW(), 'Massa (média), molho, queijo, presunto, tomate, azeitona, orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Palmito', 43.0, 17.0, NOW(), 'Massa (média), molho, queijo, presunto, champignon, palmito (pupunha), orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Paulista', 37.0, 14.0, NOW(), 'Massa (média), molho, queijo, presunto, champignon, milho verde, ervilha, orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('POrtuguesa', 37.0, 14.0, NOW(), 'Massa (média), molho, queijo, presunto, cebola, pepino, ovo cozido, orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Quatro Queijos', 39.0, 15.0, NOW(), 'Massa (média), molho, azeitona, tomate, Queijos: (Prato, Catupery, Provolone, Mussarela), orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Simples', 37.0, 14.0, NOW(), 'Massa (média), molho, queijo, presunto, tomate, calabreza picada, orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Siri', 45.0, 17.0, NOW(), 'Massa (média), molho, queijo, pepino, azeitona, siri ao molho, orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Completa', 47.0, 18.0, NOW(), 'Massa (média), molho, queijo, presunto, tomate, azeitona, milho verde, pepino, ovo cozido, calabreza picada, champignon, orégano', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('X-Salada', 20.0, 10.0, NOW(), 'Pão, maionese, hamburguer, queijo, presunto, alface, tomate, milho, ervilha, (Opção no prato com fritas)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('X-Burguer', 19.0, 9.0, NOW(), 'Pão, maionese, hamburguer, queijo, presunto, (Opção no prato com fritas)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('X-Egg', 24.0, 14.0, NOW(), 'Pão, maionese, hamburguer, queijo, presunto, alface, tomate, milho verde, ervilha, ovo, (Opção no prato com fritas)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Bauru', 19.0, 9.0, NOW(), 'Pão, maionese, queijo, presunto, alface, tomate, milho verde, ervilha, (Opção no prato com fritas)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Americano', 27.0, 17.0, NOW(), 'Pão, maionese, queijo, presunto, alface, tomate, pepino, ovo, bacon, cebola assasa, (Opção no prato com milho verde, ervilha,fritas)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('X-Picanha', 30.0, 20.0, NOW(), 'Pão, maionese, queijo, alface, tomate, picanha, (Opção no prato com milho verde, ervilha, fritas)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Batata Grande', 28.0, 0.0, NOW(), 'Contém mais ou menos 1Kg)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Batata Grande Especial', 38.0, 0.0, NOW(), 'Contém mais ou menos 1Kg, com bacon e queijo)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Batata Média', 19.0, 0.0, NOW(), 'Contém mais ou menos 500g)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Batata Média Especial', 29.0, 0.0, NOW(), 'Contém mais ou menos 500g, com bacon e queijo)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Batata Pequena', 17.0, 0.0, NOW(), 'Contém mais ou menos 300g)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Batata Pequena Especial', 24.0, 0.0, NOW(), 'Contém mais ou menos 300g, com bacon e queijo)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Refrigerante 1l', 6.0, 0.0, NOW(), 'Refrigerante 1 litro)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Refrigerante 2l', 12.0, 0.0, NOW(), 'Refrigerante 2 litros)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, average_price, small_price, date, description, img_url) VALUES ('Refrigerante 600ml', 5.0, 0.0, NOW(), 'Refrigerante 600ml)', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');


INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (21, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (22, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (23, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (24, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (25, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (26, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (27, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (28, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (29, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (30, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (31, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (32, 4);

INSERT INTO tb_order(order_status, latitude, longitude, moment) VALUES (0, 213123, 12323, NOW());
INSERT INTO tb_order(order_status, latitude, longitude, moment) VALUES (1, 3453453, 3534534, NOW());

INSERT INTO tb_product_order (product_id, order_id) VALUES (1, 1);
INSERT INTO tb_product_order (product_id, order_id) VALUES (2, 1);
INSERT INTO tb_product_order (product_id, order_id) VALUES (2, 2);
INSERT INTO tb_product_order (product_id, order_id) VALUES (2, 3);
